menu:
  Home: /
  Archives: /archives

widgets:
- category
- tag

excerpt_link: Read More

twitter:
  username: davidroberts63
  show_replies: false
  tweet_count: 5

addthis:
  enable: true
  pubid:
  facebook: false
  twitter: true
  google: false
  pinterest: fa;se

fancybox: true

google_analytics:
rss:

comment_provider: disqus
